# Generated by Django 3.2.7 on 2021-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
