# Generated by Django 3.2.6 on 2021-12-14 09:23

from django.db import migrations, models
import mapserver.models.job
import mapserver.models.project


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_index', models.SmallIntegerField()),
                ('matrix', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('pdb', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('environment', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('structural_data', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('hydrogen_bonds', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('pqr', models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('logs', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('Q', 'Queue'), ('R', 'Running'), ('E', 'Error'), ('F', 'Finished')], default='S', max_length=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('date_init', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=mapserver.models.project.get_map_id, max_length=12, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('pdb', models.FileField(upload_to=mapserver.models.project.pdb_path)),
                ('info', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
