# Generated by Django 3.2.7 on 2021-09-10 06:14

from django.db import migrations, models
import django.db.models.deletion
import mapserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(default=mapserver.models.get_map_id, max_length=12, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('pdb', models.FileField(upload_to=mapserver.models.pdb_path)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.SmallIntegerField()),
                ('matrix', models.FileField(blank=True, null=True, upload_to=mapserver.models.matrix_path)),
                ('info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Q', 'Queue'), ('R', 'Running'), ('E', 'Error'), ('F', 'Finished')], default='Q', max_length=1)),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.map')),
            ],
        ),
    ]
