# Generated by Django 3.0.3 on 2020-02-05 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mapserver.models.identity
import mapserver.models.project


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.CharField(default=mapserver.models.identity.random_id, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)])),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'identities',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mapserver.models.project.compute_dir)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='JobRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_label', models.CharField(max_length=100)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.DataType')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.JobType')),
            ],
            options={
                'unique_together': {('data_label', 'job_type')},
            },
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Upload')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Job')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.JobRecipe')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.JobType'),
        ),
    ]
