# Generated by Django 3.0.2 on 2020-03-11 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapserver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mapserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.CharField(default=mapserver.utils.rs10, max_length=10, primary_key=True, serialize=False)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
    ]
