# Generated by Django 3.2.7 on 2021-11-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('mapserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.identity'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.project'),
        ),
    ]
