# Generated by Django 3.2.6 on 2022-02-17 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_init',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('F', 'Finished')], default='C', max_length=1),
        ),
    ]
