# Generated by Django 3.2.7 on 2021-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='model_number',
            new_name='model_index',
        ),
    ]
