# Generated by Django 3.2.7 on 2021-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
