# Generated by Django 3.0.2 on 2020-03-11 20:27

from django.db import migrations, models
import django.db.models.deletion
import mapserver.models
import mapserver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0002_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(default=mapserver.utils.rs12, max_length=12, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('pdb', models.FileField(upload_to=mapserver.models.pdb_path)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Identity')),
            ],
        ),
    ]
