# Generated by Django 4.0 on 2022-04-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0003_auto_20220217_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_init']},
        ),
    ]
