# Generated by Django 3.2.7 on 2021-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('Q', 'Queue'), ('R', 'Running'), ('E', 'Error'), ('F', 'Finished')], default='S', max_length=1),
        ),
    ]
