# Generated by Django 3.2.7 on 2021-09-27 20:25

from django.db import migrations, models
import mapserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0003_project_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pdb',
            field=models.FileField(blank=True, null=True, upload_to=mapserver.models.compute_path),
        ),
    ]
