# Generated by Django 3.0.3 on 2020-06-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mapserver', '0003_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
