# Generated by Django 3.2.7 on 2021-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0003_rename_model_number_job_model_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
