# Generated by Django 3.2.7 on 2021-09-30 11:20

from django.db import migrations, models
import mapserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0004_job_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hydrogen_bonds',
            field=models.FileField(blank=True, null=True, upload_to=mapserver.models.compute_path),
        ),
        migrations.AddField(
            model_name='job',
            name='structural_data',
            field=models.FileField(blank=True, null=True, upload_to=mapserver.models.compute_path),
        ),
    ]
