# Generated by Django 4.0 on 2022-04-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_init']},
        ),
    ]
