# Generated by Django 4.0 on 2022-02-16 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_init',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('E', 'Error'), ('F', 'Finished')], default='C', max_length=1),
        ),
    ]
