# Generated by Django 3.0.2 on 2020-06-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0004_auto_20200623_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGLColorScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('help', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NGLRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('options', models.TextField()),
                ('help', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('options', models.TextField()),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mapserver.NGLColorScheme')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.Map')),
                ('representation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mapserver.NGLRepresentation')),
            ],
            options={
                'unique_together': {('map', 'name')},
            },
        ),
    ]
