# Generated by Django 3.0.3 on 2020-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0005_nglcolorscheme_nglrepresentation_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='selection',
            field=models.CharField(default='all', max_length=200),
        ),
    ]
