# Generated by Django 3.2.7 on 2021-10-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0005_auto_20210930_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
