# Generated by Django 4.0 on 2022-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0005_project_date_init_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
