# Generated by Django 3.2.7 on 2021-10-22 12:34

from django.db import migrations, models
import mapserver.models.job


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0005_job_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pqr',
            field=models.FileField(blank=True, null=True, upload_to=mapserver.models.job.compute_path),
        ),
    ]
