# Generated by Django 3.2.7 on 2021-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0006_job_pqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
