# Generated by Django 3.0.2 on 2020-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0006_representation_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nglcolorscheme',
            name='keyword',
            field=models.CharField(default='dupa', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
