# Generated by Django 3.0.2 on 2020-06-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0007_nglcolorscheme_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='nglrepresentation',
            name='keyword',
            field=models.CharField(default='dupa', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
