# Generated by Django 3.0.2 on 2020-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0008_nglrepresentation_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
