# Generated by Django 3.0.3 on 2020-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0009_representation_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nglrepresentation',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
