# Generated by Django 3.0.3 on 2020-07-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0010_auto_20200702_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='representation',
            unique_together=set(),
        ),
    ]
