# Generated by Django 3.0.3 on 2020-07-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0011_auto_20200702_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='visible',
        ),
    ]
