# Generated by Django 3.0.3 on 2020-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0012_remove_representation_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='nglcolorscheme',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
