# Generated by Django 3.1.2 on 2020-10-20 12:01

from django.db import migrations, models
import django.db.models.deletion
import mapserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0013_nglcolorscheme_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.FileField(blank=True, null=True, upload_to=mapserver.models.matrix_path)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapserver.map')),
            ],
        ),
    ]
