# Generated by Django 3.1.2 on 2020-10-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0014_mapmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmodel',
            old_name='mapa',
            new_name='map',
        ),
    ]
