# Generated by Django 3.1.2 on 2020-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0015_auto_20201020_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
