# Generated by Django 3.1.2 on 2020-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0016_mapmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
