# Generated by Django 3.1.2 on 2020-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapserver', '0017_map_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
